### ISSUE TITLE
Add email sending capabilities to csis system

### ISSUE THREAD

**Issue by fgeyer16** [clarity-h2020/docker-drupal#10]
Install SMTP module and provide SMTP Server account for sending mails, e.g. the SMTP account used by cat.clarity-h2020.eu.

**Comment by fgeyer16** [comment]
I installed the SMTP module now. So we only need a email account and its server settings and credentials.

**Comment by p-a-s-c-a-l** [comment]
Please re-use clarityh2020@gmail.com (also used for [clarity_h2020 twitter account](https://twitter.com/clarity_h2020) account) or register another gmail account.

**Comment by fgeyer16** [comment]
Can anybody tell me where I can find the credentials for that account? Or send them to me by email?

**Comment by fgeyer16** [comment]
I just tested email sending with another smtp server, but it failed because the smtp server could not be reached. Are there some settings on the server itself,which could prevent drupal connecting to a smtp server (firewall etc.)?

**Comment by fgeyer16** [comment]
It seems that TLS and port 587 are working but SSL and port 465 not. Scine gmail is using first we can use the clarityh2020@gmail.com account. Who knows the credentials?

**Comment by p-a-s-c-a-l** [comment]
We are currently evaluating the possibility to setup our own mail server based on https://github.com/tomav/docker-mailserver

But then we definitely need to open the required ports in the corporate firewall. @Itsman-AT

**Comment by Itsman-AT** [comment]
Could you please update me from which domain/server you want to reach which smtp? Are we trying to use a gmail account or do we want to use the AIT DMZ MX? I will then ask the Helpdesk to support us further.

**Comment by p-a-s-c-a-l** [comment]
Sending mails via SMTP does not work, Drupal shows a generic error message:

**Unable to send email. Contact the site administrator if the problem persists.**

Although there is an option to enable debugging (Checking this box will print SMTP messages from the server for every e-mail that is sent.), the debug log printed in the browser windows disappears so fast (because the page is instantly reloaded), that there's no chance to read the log messages! The /admin/reports/dblog does not provide any further information

@Itsman-AT 
smtp.googlemail.com:465 See http://gmail.google.com/support/bin/answer.py?answer=13287 for more information on configuring for use with Gmail. 

But in theory port 587 should work, too (see https://github.com/clarity-h2020/docker-drupal/issues/10#issuecomment-425363922)

**Comment by p-a-s-c-a-l** [comment]
Now, after allowing 'insecure apps' to access the goggle account, sending mails on behalf of CSIS does work. However, this can only be an **intermediate solution for developing and testing** until we've setup out own mail server!

@negroscuro 
Can you lease check possibilities for adding a TXT Record (see mail from 04.10.2018) to the domain?

**Comment by p-a-s-c-a-l** [comment]
Emails are now sent from noreply@csis.myclimateservice.eu
