### ISSUE TITLE
/app/web/sites/default/files ownership and permissions

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#109]
Please see https://csis.myclimateservice.eu/admin/config/media/image-styles/manage/geofield_map_default_icon_style

It's not working, no idea why.

https://csis.myclimateservice.eu/admin/config/media/image-styles/manage/icon_for_a_map_ works, so it's not critical, but this has worked before. I suspect that something might have changed in permissions, because I also see this in the log:

![image](https://user-images.githubusercontent.com/2961790/64190693-38bf4500-ce77-11e9-8824-10b50f54a570.png)

- "Failed to create style directory: public://styles/geofield_map_default_icon_style/public/core/modules/image"
- "Failed to create style directory: public://styles/geofield_map_default_icon_style/public/hazard-icons"
- "Warning: unlink(/app/web/sites/default/files/styles/icon_for_a_map_/public/core/modules/image/sample.png): Permission denied in Drupal\Core\File\FileSystem->unlink()"

and such

Did anyone change the directory permissions?

**Comment by DenoBeno** [comment]
It's worse than I thought. Today I tried to take a screenshot - saving failed, probably a permission issue again.

**Comment by patrickkaleta** [comment]
Just sat down with Denis for quite a bit and checked the permissions of the files folder (`/app/web/sites/default/files`) and noticed that the permissions are not uniformly set (most files/folders belong to `docker`, a few belong to `www-data`, some folders have **write-permission for all**), which is mostprobably the reason for this problem:
![files-folder-permissions](https://user-images.githubusercontent.com/42167036/64331797-bf893480-cfd3-11e9-95bc-b65251dfe17d.png)

After searching through the web, we came to the conclusion that `www-data` should be set as either user or group of those files/folders, **so for now we did the following:**
- `chown docker:www-data`
- for directories `chmod 2775`
- for files `chmod 2664`

**only for the following directories** and the files they include (only those containing images, since for some folders we are not sure how the configuration should look like, like e.g.: `color`, `css`, `js`, `languages`, `translations`,... ):
- 2018-10
- 2018-11
- 2019-01
- 2019-02
- 2019-04
- 2019-05
- 2019-08
- 2019-09
- adaptation_options
- geofieldmap_icons
- hazard-icons
- inline-images
- pictures
- report-images
- showcases
- solution_offers
- twins

Unfortunately, we couldn't find any useful and up-to-date Drupal documentation on how to correctly set permissions on the `files` folder, especially when also using Docker. 
@fgeyer16 we hope that maybe you have more experience with this kind of issue?

**Comment by patrickkaleta** [comment]
> Please see https://csis.myclimateservice.eu/admin/config/media/image-styles/manage/geofield_map_default_icon_style
> 
> It's not working, no idea why.

This is now fixed after the changes described above. But I wouldn't close this issue yet, since I don't think that we are done with fixing the permission settings for the `files` folder.

**Comment by DenoBeno** [comment]
@fgeyer16 , @DanielRodera : could one of you take this over?

**Comment by DenoBeno** [comment]
This is important - not quite but almost a showstopper. @DanielRodera , @fgeyer16 - can one of you please take a look at it?
---------------
Someone has to take a good look at the permissions, decide what they should be, white change the permissions accordingly (also in git repository!) and write down instructions for the future reference.

I suspect that everything under /sites/default/files should be:

- owner: either docker:www-data or www-data:www-data 
- directories permissions: 2775
- files permissions: 2664

This is definitely the case for the images and uploaded files.

**Comment by DenoBeno** [comment]
Any progress? Now the geofield_map_default_icon_style works, but not the "icons for the maps". I don't need the other one, but it's a bad sign.

**Comment by patrickkaleta** [comment]
@fgeyer16 you could probably have some advice for this, since you could check how the permissions are set on other Drupal projects you're working on.

**Comment by fgeyer16** [comment]
I checked some other drupal projects now.
Permissions on folders were 750 or 755 on files 740 or 744 owner and group where www-data:www-data
So I can give no advice how to handle ownership with docker. but i found this

> Summarizing the permissions #
> drupal_admin: the user on the server that administrates Drupal, not necessarily is the root.
> site_admin: the owner of the hosted site (a customer)
> Ownership #
> Core modules/themes files and directories: drupal_admin:www-data
> Hosted sites modules/themes/files files and directories: site_admin:www-data
> 
> Permissions #
> Core modules/themes directories: rwxr-x---
> Core modules/themes files: rw-r-----
> Hosted sites modules/themes directories: rwxr-x---
> Hosted sites modules/themes files: rw-r-----
> Hosted sites "files" directory: rwxrwx---
> Hosted sites files under "files" directories: rw-rw----
> Hosted sites subdirectories under "files" directories: rwxrwx--

[here](https://www.drupal.org/node/244924)

**Comment by DenoBeno** [comment]
OK, let me try it this way:

root@3b8d70db32d6:/app/web/sites/default# find files/ -exec chown docker:www-data {} \;
root@3b8d70db32d6:/app/web/sites/default# find files/ -type d -exec chmod 770 {} \;
root@3b8d70db32d6:/app/web/sites/default# find files/ -type f -exec chmod 660 {} \;

This *should* be exactly what we need, but please yell if anything stops working now.

**Comment by p-a-s-c-a-l** [comment]
Please don‘t change owner and groups of the dirs Apps, modules, etc! This will Mess Up composer, git, etc.! 

Owner and group docker is correct for **all** Files except files uploaded via api or ui.

Von meinem iPhone gesendet

**Comment by DenoBeno** [comment]
what are the correct ownerships & privileges on these?

What we have now gives the same privileges to www-data and to docker user and no privileges to anyone else. This *should* work for anything under "files".

**Comment by p-a-s-c-a-l** [comment]
For /app/web/sites/default/files it's ok IMHO. For other directories it should be rwx for user and group docker. Please note that if you want to use composer or git to update modules and apps from *inside* the container, you have to append `--user 999` (docker uid) to your `docker exec` commands otherwise all operations performed *inside* the container will be done as root and thus all modified / created files will be owned by root. This is a common docker pitfall and often leads to a mess-up of file permissions/ownership in containers.

However, one should be aware that the user and group ids in docker containers are not necessarily the same as the user and groups ids on the host operating system! For group and user docker I made sure that those ids match, but for www-data they may be different. So if somebody tries to change ownership directly on the host mounted volume /docker/100-csis/drupal-data/web/sites/default/files from *outside* of the container this will probably set the wrong uids und gids *inside* the container. So maybe that's the problem @DanielRodera is facing [here](https://github.com/clarity-h2020/csis/issues/85#issuecomment-533620790)?

**Comment by DenoBeno** [comment]
I changed it within the container. I think that it's fine as it is now, but
please yell if anything stops working.

**Comment by DenoBeno** [comment]
> Please don‘t change owner and groups of the dirs Apps, modules, etc! This will Mess Up composer, git, etc.! Owner and group docker is correct for **all** Files except files uploaded via api or ui. Von meinem iPhone gesendet

Ah, clear. 

Everything except for the data in "files" is read-only for the web server and apparently the "docker:docker" doesn't bother it. I do hope that nothing there is world-writable, one of these days someone should double check these privileges too, for security reasons.

Data under "files" is normally written on run time, by web server. Thus the web server has to be able to write to it... The only problem could be if someone is misusing this directory to write data to it through some other mechanism and not through web server. If so, we should find out which directories are affected, change the owner to assure things work and then re-design whatever is managing and using this data to look for it in some other place.

**Comment by DenoBeno** [comment]
Since nobody complained, I suppose this is OK now.
