### ISSUE TITLE
Make expert study type only available for expert"s

### ISSUE THREAD

**Issue by fgeyer16** [clarity-h2020/docker-drupal#115]
After talking with @Andrea4ad , normal users (non climate expert users) should only be able to create studies which do not need experts input (screening studies). Otherwise they may be confused or worse scared off if they see a lot of needed input they have no idea what it is about.

Since study types are taxonomy terms I think this can be achieved by using the module [permission by term](https://www.drupal.org/project/permissions_by_term) and different roles for normal users and climate experts.

I propose to make the authenticated user role to the normal user and create an Expert role to which user can be upgraded if they are experts.

I mark this as showstopper since on European week in October the audience will be normal users.

**Comment by DenoBeno** [comment]
Sounds like a good idea.

**Comment by p-a-s-c-a-l** [comment]
> normal users (non climate expert users) should only be able to create studies

1st we have to make sure that users actually **will** be able to create studies by October, so putting this issue on hold until the system is actually functional.

**Comment by DenoBeno** [comment]
@fgeyer16 : are you going to implement this? Or are you asking @patrickkaleta to do it?

**Comment by fgeyer16** [comment]
I was already talking about this with @patrickkaleta yesterday and he said he will test it when he installs the other requested modules. 
Created the ticket for Documentation and not to lose track

**Comment by patrickkaleta** [comment]
Yes I will take care of this, once more urgent issues are resolved. 

A related feature-request would be #82 , since it will use the same proposed module [Permissions by Term](https://www.drupal.org/project/permissions_by_term), so I'll try to tackle both of them at once.

**Comment by patrickkaleta** [comment]
Removing "on-hold", since we need to (IMO) now also focus on permissions and User/Group roles if we want to allow real users to use the CSIS. And for that [Permissions by term](https://www.drupal.org/project/permissions_by_term) module seems very promising. I've installed and enabled this module.

As [suggested](https://github.com/clarity-h2020/docker-drupal/issues/115#issue-494261281) I've created a new User role `Expert` and set these permissions for the StudyType terms:

| Study Type | Authenticated user | Expert | Admin |
| ------------- | ------------- | ------------- | ------------- |
| Adv. Screening: Urban Infr.  | ✔️   | ✔️   | ✔️    |
| Basic Screening: General  | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark:  |
| Expert: General  | ❌   | ✔️   | :heavy_check_mark: |
| Expert: Urban Infr.  | :x:  | :heavy_check_mark:  | :heavy_check_mark:  |
| Expert: Transp. Infr.  | :x:  | :heavy_check_mark:  | :heavy_check_mark:  |
| TEST screening: Test  | :x:  | :x:  | :heavy_check_mark:  |
| TEST Expert: Test  | :x:  | :x:  | :heavy_check_mark:  |

So, if for example an ordinary authenticated user (without any additional roles) creates a new study, he can only select between the two Screening Study types (the others are not visible).

@fgeyer16: Do we need to re-create all User roles across all other platforms (Expert-profiles, marketplace,...) or can some of them just exist "locally" like the new `Expert` role in the CSIS?

**Comment by patrickkaleta** [comment]
This can be closed now. I talked to @fgeyer16 and he said that not all users and user roles need to be generated across all our platforms (especially when they are just meant to be used for testing purposes)
