### ISSUE TITLE
Adaptation Twins not working

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#117]
See [here](https://csis.myclimateservice.eu/study/33/step/1457/view/twins) and [there](https://csis.myclimateservice.eu/study/35/step/1451/view/twins). Not sure if "Adaptation Twins"  are available at all, if not , we have to remove them from the GL-Step templates.

**Comment by patrickkaleta** [comment]
> See here and there. Not sure if "Adaptation Twins" are available at all, if not , we have to remove them from the GL-Step templates.

@DenoBeno those steps mentioned by Pascal have the [Twins: Adaptation options View](https://csis.myclimateservice.eu/admin/structure/views/view/twins_adaptation_options?destination=/admin/structure/views) assigned to them (with arguments), so the Adaptation Twins should be available? Or aren't you finished with that View yet?

In the contextual filters of that View I can see that a fixed value of 1029 is used. Where you maybe just testing something and forgot to revert that afterwards?

**Comment by DenoBeno** [comment]
Adaptation twins should be available. They worked the last time I checked. And the ID was not fixed. Maybe we had a regression where the last version was lost?

I'll fix this.

**Comment by DenoBeno** [comment]
Well, they aren't included in the template. 

![image](https://user-images.githubusercontent.com/2961790/65859646-f18a7e00-e368-11e9-9190-0217f9a7e03b.png)

They do exist and AFAIK work, see https://csis.myclimateservice.eu/study/17/step/1315/view/table and https://csis.myclimateservice.eu/study/17/step/1315/view/twins

![image](https://user-images.githubusercontent.com/2961790/65859777-39110a00-e369-11e9-917a-4cd77971a9e4.png)

Note: some adaptation options must be listed in the data package and the table view must be used to choose some - otherwise the twin view will not show anything.

**Comment by DenoBeno** [comment]
OK, I found the issue: the "adaptation options" work that I have made aimed at "Identify adaptation options" step, not at the implementation. The same functionality *could* in principle be used in "implementation", but there is no implementation in the screening step AFAIK. 

Thus: I could make this work, but the question is what we really want?

**Comment by DenoBeno** [comment]
Following a discussion today, this seems to be a non-issue. Adaptation options table & twins work as designed in the "identification" step and that's all we expect from them at the moment. 

Adding a tab with "external application" is a different issue, something Patrick will take care of.

**Comment by DenoBeno** [comment]
@p-a-s-c-a-l : please double-check and close if all is OK.

**Comment by p-a-s-c-a-l** [comment]
is working now.
