### ISSUE TITLE
Showing and changing presets outside the study group context

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#134]
Somewhat related to https://github.com/clarity-h2020/map-component/issues/59

I have implemented a simple view that shows presets and allows the users to edit them while in the GL-step context and not in the group context. This allows users to quickly change the presets and take screenshots of various preset combinations whenever they feel like it.

Result:
![grafik](https://user-images.githubusercontent.com/2961790/66125644-d7120800-e5e7-11e9-9a52-f99ad1455654.png)

![grafik](https://user-images.githubusercontent.com/2961790/66125683-ec873200-e5e7-11e9-8447-632f271a6c8c.png)

Currently this is defined as a block and attached to all "map pages" and a "global: view area" header to this view: https://csis.myclimateservice.eu/admin/structure/views/view/view_mode_for_gl_step/edit/page_3

The view providing the data is called "View presets and edit": https://csis.myclimateservice.eu/admin/structure/views/view/view_presets_and_edit/edit/block_1

**Comment by patrickkaleta** [comment]
See comment [#1](https://github.com/clarity-h2020/docker-drupal/issues/135#issuecomment-572463144) and [#2](https://github.com/clarity-h2020/docker-drupal/issues/135#issuecomment-572479816) for recent updates relevant to this issue.

**Comment by p-a-s-c-a-l** [comment]
Hm, when visiting https://csis.myclimateservice.eu/study/30/step/1613/view/maps I get now:

![grafik](https://user-images.githubusercontent.com/1788226/72058026-b553ab80-32cf-11ea-86d1-b1073e917fb5.png)

**Comment by patrickkaleta** [comment]
The real problem is, that Study 30 has been removed. The error message is just very misleading.

**Comment by p-a-s-c-a-l** [comment]
OK, what we would need here is to select one of the named scenario presets created by the user in the study/context tab, but not to edit existing scenario presets or adding new ones.

**Comment by patrickkaleta** [comment]
> OK, what we would need here is to select one of the named scenario presets created by the user in the study/context tab, but not to edit existing scenario presets or adding new ones.

I agree, that would be a much better solution.

Unfortunately, the Scenario presets are [Paragraphs](https://www.drupal.org/project/paragraphs) (basically a special kind of content similar to Nodes), that don't offer any type of selection, so implementing this will be tricky.

### I think this could work:
- new field "Active scenario" or "Selected scenario" of type `text_list`, which will store the ID of the selected Scenario. (Allowed values initially empty, filled later dynamically by our csis_helpers module)
- raise cardinality of current field "Study presets" from just 1 to 5-10. Owner will then define a couple of presets in study/context tab
- in HC/maps tab user will only be able to select between one of the defined scenarios
- the selected/active scenario will be stored and available in the `studyInfo` object just like it is right now, so the map component doesn't need to be adjusted

(@fgeyer16 do you see any potential on how to get this done easier?) 

Quickly tested this locally and it seems to work. That's how it could look like:
currently selected Scenario shown to user in e.g. HC/maps tab
![select-available-scenario](https://user-images.githubusercontent.com/42167036/73082844-79713680-3eca-11ea-87fb-15fe7ffa7f4d.png)
that's what the user would get when clicking on "edit scenario" (probably should change that to "change scenario" or something)
![select-available-scenario-form](https://user-images.githubusercontent.com/42167036/73082888-8aba4300-3eca-11ea-8222-c0056e245d3b.png)

**Comment by patrickkaleta** [comment]
Proposed changes in my previous comment are now implemented. 

Study owners can now define up to 5 scenarios (rather start low, since raising the limit is no problem, but reducing it can be problematic), which then appear in the select lists of the individual GL-steps.

**Involved elements in this new feature:**
- [view](https://csis.myclimateservice.eu/admin/structure/views/view/study_scenarios/edit/block_1) returning active scenario
- [view](https://csis.myclimateservice.eu/admin/structure/views/view/view_presets_and_edit/edit/block_2) displaying current selection and select button
- [csis_helpers_allowed_values_function](https://github.com/clarity-h2020/csis-helpers-module/blob/dev/csis_helpers.module) generates the select list
- declared the "allowed values" function via [Config import](https://csis.myclimateservice.eu/admin/config/development/configuration/single/import) for the Field storage type
- new field [Active Scenario](https://csis.myclimateservice.eu/admin/group/types/manage/study/fields/group.study.field_active_scenario) stores currently selected Scenario ID

**Comment by patrickkaleta** [comment]
IMO this issue can now be closed.
