### ISSUE TITLE
No selection of Study Scenarios in Basic Screening Studies

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#135]
Cannot select study scenarios (fka "presets") in studies of type "Basic Screening: General". See https://github.com/clarity-h2020/csis/issues/109#issuecomment-564940916

**Comment by patrickkaleta** [comment]
Seems like the View responsible for the study scenario selection is not yet configured for the **Study-Context tab** but only for the **individual GL-steps tabs**. I'll take care of this.

~But if I remember correctly the study scenario selection used to be part of the overall **Context edit-form**. Why was it removed from there?~

**Update:** Ok, I understand now. Study scenarios were removed from the general Context edit-form, because some Study types were not supposed to have any. But this requirement [changed](https://github.com/clarity-h2020/csis/issues/109#issuecomment-564940916), so now **all** studies need a study scenario. 
Therefore, I think it will be best to add the study scenario selection back to the Context edit-form and on the top of the **Context** tab just to show the currently selected scenario instead.

**Comment by patrickkaleta** [comment]
IMO this is now fixed in a suitable manner (probably now also #134?). For all Study types it is now possible to select a Study scenario in the Study-Context tab via the Context edit-form.

**Affected/changed (form) displays:**
- [Study Context form](https://csis.myclimateservice.eu/admin/group/types/manage/study/form-display/context)
- [Study Context display](https://csis.myclimateservice.eu/admin/group/types/manage/study/display/context)
- [Study scenario (aka Presets) display](https://csis.myclimateservice.eu/admin/structure/paragraphs_type/variable_set/display/preview)
