### ISSUE TITLE
Workflow for adding data packages fails due to wrong "next" link.

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#136]
Months ago I configured a workflow for adding data packages on https://csis.myclimateservice.eu/admin/config/workflow/forms_steps/edit/data_package_form_steps?destination=/admin/config/workflow/forms_steps

I tried to enable it again yesterday and the result is:

1. adding the DP on /dp/add works ok
2. on second step, "access denied" error is shown. This error is misleading, the real issue is that the "next" link drops the unique ID of the workflow.

Example:
- Existing 1-st step
https://csis.myclimateservice.eu/dp/add/e7d91ae7-4796-4869-aaab-650830dbad52
- "next" leads to https://csis.myclimateservice.eu/DP/step2
- "next" *should* lead to https://csis.myclimateservice.eu/DP/step2/e7d91ae7-4796-4869-aaab-650830dbad52

@fgeyer16 : any idea why this is happening on csis? We don't have this issue on DRIVER+ pos.

**Comment by fgeyer16** [comment]
I do not have this issue on market place as well.
I checked the workflow list (https://csis.myclimateservice.eu/admin/config/workflow/forms_steps/workflows/list) and it seems the module starts creates a new step 1 every time. Strange needsfurther investigations concerning redirection. 
Any redirect moduleinstalled? I did not se any but ask to be sure.

**Comment by DenoBeno** [comment]
None that I know of. Maybe Patrick knows more.

fgeyer16 <notifications@github.com> schrieb am Mo., 20. Jan. 2020, 07:33:

**Comment by patrickkaleta** [comment]
I will keep that in mind and try to investigate this issue on my local instance of the CSIS

**Comment by DenoBeno** [comment]
@patrickkaleta says that he's not aware of any special modules that woudl interfere with the URIs. 

Could it be something obvious, e.g. that I forgot to configure something that's needed for this to work? Or some patch?

This is what I posted as a bug report on drupal.org back in september 2019:

 - https://www.drupal.org/project/forms_steps/issues/3084693

Not very helpful I'm afraid. :-(

**Comment by patrickkaleta** [comment]
So none of our modules or any other contributed module is causing this problem (as far as I can tell). 

The problem is somewhere deep within the Forms Steps module itself and/or Drupal Core. The **WorkflowManager** of this module tries to find the fitting workflow by searching for a triplet (**entity_type, bundle, entity_id**):


```
$workflows = $this->entityTypeManager
   ->getStorage(Workflow::ENTITY_TYPE)
   ->loadByProperties(
     [
       'entity_type' => $entity->getEntityTypeId(),
       'bundle' => $entity->bundle(),
       'entity_id' => $entity->id(),
     ]
 );
```

I checked the values it's using and they are correct (they match what can be seen in the [BE](https://csis.myclimateservice.eu/admin/config/workflow/forms_steps/workflows/list)). But for some strange reason, no workflow is found, which in the end leads to our error.

**Even weirder,** when I remove one of the 3 properties above (doesn't matter which one!), then all of the sudden the workflow is found and everything works just fine...

**Comment by fgeyer16** [comment]
Hm I patched src/Forms/FormsStepsAlter.php to be able to redirect to the workflows entity:
```
134         $parameters = $route->getParameters()->all();
+           $parameters[$form_state->getformObject()->getEntity()->getEntityTypeId()] =$form_state->getformObject()->getEntity()->id();
            $form_state->setRedirect($redirection_target, $parameters);
```
 @patrickkaleta can you try out what happens on your local csis instance if you apply this patch as well? I do not think this solves it but who knows...

**Comment by patrickkaleta** [comment]
> Hm I patched src/Forms/FormsStepsAlter.php to be able to redirect to the workflows entity:
> 
> ```
> 134         $parameters = $route->getParameters()->all();
> +           $parameters[$form_state->getformObject()->getEntity()->getEntityTypeId()] =$form_state->getformObject()->getEntity()->id();
>             $form_state->setRedirect($redirection_target, $parameters);
> ```
> 
> @patrickkaleta can you try out what happens on your local csis instance if you apply this patch as well? I do not think this solves it but who knows...

I will try it and let you know of the result.

**Comment by fgeyer16** [comment]
> I checked the values it's using and they are correct (they match what can be seen in the BE). But for some strange reason, no workflow is found, which in the end leads to our error.
> 
> Even weirder, when I remove one of the 3 properties above (doesn't matter which one!), then all of the sudden the workflow is found and everything works just fine...

@patrickkaleta can you make a kint(), var_dump, \Drupal::logger, whatever to print out the $Workflows varible created with all parameters and with only two?

**Comment by patrickkaleta** [comment]
> > I checked the values it's using and they are correct (they match what can be seen in the BE). But for some strange reason, no workflow is found, which in the end leads to our error.
> > Even weirder, when I remove one of the 3 properties above (doesn't matter which one!), then all of the sudden the workflow is found and everything works just fine...
> 
> @patrickkaleta can you make a kint(), var_dump, \Drupal::logger, whatever to print out the $Workflows varible created with all parameters and with only two?

using all the 3 parameters I get `Null`, since no workflows are found. Using just two parameters, I get the workflow object:
![workflows-entity](https://user-images.githubusercontent.com/42167036/73160775-2d044180-40ea-11ea-9cc7-2fdf20546256.png)

The shown values (id, bundle, form_mode,...) match what is found on the "Workflow Instances list".

**Comment by patrickkaleta** [comment]
The problem is that a wrong query is being generated by Drupal and therefore no workflow is found (the `bundle` should be 'data_package' ):
![postgres-query-bug](https://user-images.githubusercontent.com/42167036/73179117-f858b000-4112-11ea-9dde-327810806a7f.png)

**Apparently it's a known Drupal Core bug (posted 4 years ago) affecting sites with a Postgres db** ([Issue description](https://www.drupal.org/project/drupal/issues/2734445)). It hasn't been fixed since then and it is still unclear what exactly causes this bug.

In our case it is caused when using 3 parameters, but according to the issue description it can also happen when using only 2. We can fix the problem for the Forms steps by adding our own custom patch and quering just by `entity_type` and `entity_id`, but this Core bug affects the complete Drupal system and honestly I'm surprised we didn't run into problems earlier.

A patch for the Core bug has been proposed with no feedback so far, so I will try to test it myself.

**Comment by p-a-s-c-a-l** [comment]
Is this issue still relevant?

**Comment by patrickkaleta** [comment]
> Is this issue still relevant?

Doesn't seem to be.
