### ISSUE TITLE
Study checklist should be refreshed after selecting a study area

### ISSUE THREAD

**Issue by therter** [clarity-h2020/docker-drupal#149]
After selecting a study area, the text "study area: not selected" is still shown on the right side

![Bildschirmfoto vom 2020-06-08 09-36-19](https://user-images.githubusercontent.com/1788509/84004468-e5c96f80-a96b-11ea-9534-0d5a5dd1425d.png)

I don't know what is the best way to do this. Perhaps the save change button can somehow do a refresh of the study checklist. What do you think Patrick?

**Comment by patrickkaleta** [comment]
> Perhaps the save change button can somehow do a refresh of the study checklist. What do you think Patrick?

Yes, that should be possible. The checklist is generated by an ordinary Drupal View and I think I've already implemented a refresh-trigger in JavaScript somewhere for a different View. Let me look for it.

**Comment by patrickkaleta** [comment]
The View responsible for the Checklist is this one [here](https://csis-dev.myclimateservice.eu/admin/structure/views/view/study_group_overview/edit/study_status_block).

To refresh a View from within JS, something like that should do the trick:
 ```
// call this function when you want to refresh a View
function updateView() {
  // make sure the Drupal object is available 
  if (typeof Drupal.views !== "undefined") {
    var instances = Drupal.views.instances;
    var myViews;

    jQuery.each(instances, function getInstance(index, element) {
      // select the desired View by its machine name
      if (element.settings.view_display_id == "study_status_block") {
        myViews = element.element_settings.selector;
        jQuery(myViews).triggerHandler('RefreshView'); // this refreshes the desired View
        // if the Drupal object is not available, use a selector of the following type:
        //jQuery(".js-view-dom-id-a7ffa3643a204dcafa126903b4bea76353ebd82eeae36f2e4cf781045f37bd71").triggerHandler('RefreshView');
        console.log("view refreshed");
      }

    });
  }
}
```

I don't know if you can access the Drupal object inside the Map component or not. If not, you can select the desired View by searching the DOM. The `.view-display-id-study_status_block` element will have the necessary id, which should like something like this (see above code for example): `js-view-dom-id-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

**Comment by patrickkaleta** [comment]
Currently, the problem is that this View is restricted by a group permission access check and the refresh via Ajax fails due to that. If the access permission is changed to something else (you can test that on the Dev instance by editing the [View](https://csis-dev.myclimateservice.eu/admin/structure/views/view/study_group_overview/edit/study_status_block) under **Block settings** -> **Access** and switching to `Permission`, `Role `or `Unrestricted`) the View can be refreshed via Ajax call.

Best alternative to the current `Group permission -> Edit group` setting, would be to switch to `Permission -> View published content` . But then the Checklist would be shown to everyone who can view the Study (currently only the Study team can see this checklist). That's not inherently bad, since they cannot do/change anything there (the "Start calculation" button is hidden separately by the csis_helpers module anyway).

**Comment by patrickkaleta** [comment]
Another alternative could be to simply directly change the HTML element after the user clicked on one of the buttons in the map component. I could give the Study area field a specific ID, so that you could select and edit the content. 

**Edit:**
I've added the ID `status-study-area` to that element. By changing the class `messages-warning` to `messages-status` and the text from "Not selected" to "Selected", you could manually update the checklist.

**Comment by therter** [comment]
> Another alternative could be to simply directly change the HTML element after the user clicked on one of the buttons in the map component. I could give the Study area field a specific ID, so that you could select and edit the content.

Thank you, I will try this approach. So that we do not have to change the permissions.

**Comment by therter** [comment]
This is now working in the dev instance
