### ISSUE TITLE
SSO needs to be improved

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#151]
I knew this was a bit tricky with CAS login and it could easily become frustrating for users, but now we have a detailed [test report](https://github.com/clarity-h2020/csis-technical-validation/issues/51#issuecomment-646681035) which highlights the main deficiencies with the current SSO/CAS implementation. In summary

> You have integrated several different sites into one, without proper session management. Going on different pages always allows me to go to a page I am not logged into, and I guess one can remember the “correct paths” after few tries, but this is against the usability principles I know.

> I have seen the video explaining how to create an account and there it says indeed that I have to login **twice**, and I still wonder - why?

This is something that has to be addressed with high priority, otherwise we will loose most user even before they got the chance to enter CSIS.

**Comment by p-a-s-c-a-l** [comment]
See also https://github.com/clarity-h2020/csis-technical-validation/issues/54#issuecomment-647956953 :

> Using the first URL (profiles...) I have to log in two times, after the first login screen it redirects to another one.

**Comment by fgeyer16** [comment]
I walked through @aitdrazen report of registering and SSO testing. Thank you for that feedback! After replaying the registering process I concluded, that session Management works as intended but user guidance and information was a little poor. Following the registration workflow I changed some things:

**Second login after setting the password:** This is necessary because after setting the password, the user is only logged in locally and CAS does not know anything about it. So the user is logged out and redirected to the cas login. There was an explanation about this fact below the Password reset form, but this was obviously to invisible for users. So I moved this info on top of the form and wrapped it in a colored warning message container.So hopefully the user will read this Information.

**Redirect after login::** after the correct CAS login the user was redirected to a strange "you are now logged in to CAS" page. I changed that to a redirect to the users profile.

**On some pages the SSO is not working:** This is how it looks like. "The correct description" would be: "as a "normal" registered user you are not allowed to login on every page. 

- Marketplace (the menu Collaboration) needs an organisation in your profile to get access. This is explained in the organisation tab when editing your profile.
- the portal (menu News and https://myclimateservoces.eu) has no functionality for normal users now. This is only accessible for users invited to write

So I pushed this information earlier in two places: 

- A short explanation in the welcome email as @aitdrazen suggested
- Messages when you visit your profile, which tell you what you ar capable to do. Since you are now redirected to your profile after login you will see this after login  

This messages appear only if you use the login link at profile.myclimateservices.eu. If you use the login links of the other pages you will be redirected to them after login in at profile.myclimateservices.eu

Please check the workflow and the messages again and let me know. YOu do not need to register a new account, just reset your password at https://profile.myclimateservices.eu.

**Comment by p-a-s-c-a-l** [comment]
Thanks @fgeyer16 ! 👍 

Any further suggestions @aitdrazen, or do you think it's o.k. now?

**Comment by aitdrazen** [comment]
> Thanks @fgeyer16 ! 👍
> 
> Any further suggestions @aitdrazen, or do you think it's o.k. now?

In my opinion, the explanations are much better now.

**Comment by p-a-s-c-a-l** [comment]
Thanks!
