### ISSUE TITLE
Local User Profiles in DEV are missing information

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#152]
Local User Profiles stored in in **DEV** instance are missing the field `basic_auth_credentials`. I don't know if this is by intention but without this information, access to EMIKAT APIs is not possible.

**Comment by patrickkaleta** [comment]
> Local User Profiles stored in in **DEV** instance are missing the field `basic_auth_credentials`. I don't know if this is by intention but without this information, access to EMIKAT APIs is not possible.

No the field should not be missing. I've only hidden it in the Edit-form. Reason was that users on DEV should be able to edit their profiles directly (since there is no connection to the central user management system) and I wanted to prevent that users edit the `basic_auth_credentials` by mistake.

But since on DEV we won't have any "normal" users, I'll undo this change to prevent any further confusion.

**Comment by patrickkaleta** [comment]
The `basic_auth_credentials` field is now visible again. Should it for a user still be empty than it's really missing and has to be added. I expect that this could be the case for some old accounts, for which we forgot to add it manually (like in the case of @ghilbrae's `angela` user).

**Comment by p-a-s-c-a-l** [comment]
Thanks, Patrick!
