### ISSUE TITLE
Unable to add hazard index tag to resource

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#154]
I've introduced a [new hazard index](https://csis-dev.myclimateservice.eu/taxonomy/hazard/storm/extreme-wind-speed/index/wind98p) and updated the respective [entity queue](https://csis-dev.myclimateservice.eu/admin/structure/entityqueue/dp_tags/hazard_indexes?destination=/admin/structure/entityqueue/dp_tags/list), but now I'm unable to add any hazard index tag to [this resource](https://csis-dev.myclimateservice.eu/node/3755):

![hazard-index](https://user-images.githubusercontent.com/1788226/85569644-0283c980-b633-11ea-98f1-623107253d52.gif)

I've rebuilt the cache but that didn't help.

**Comment by patrickkaleta** [comment]
@p-a-s-c-a-l you've created and linked the new hazard index correctly. But you're clicking on the wrong button (as was I for about half an hour). 

You need to confirm your selection of tags by clicking on the "**Add selected**" button. The "**Add Tag**" button triggers a page reload, which leads to your selection getting lost, since it was not yet explicitly confirmed (that's the workflow the Entity Browser module uses, which we have no control over). Since for the Hazards indexes the list list pretty long, the relevant "Add selected" button is hidden and you have to scroll down completely, so that you can see and click it.

I don't know why the **"Add Tag"** button is even there. It's created by the Entity Browser module, so we can't control this behaviour. Maybe we can hide that button via our csis_helpers module or by making some changes in our theme.

**Comment by p-a-s-c-a-l** [comment]
Ah, now it worked. Thanks! :-)
