### ISSUE TITLE
HTML Tags in Resource Description

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#164]
https://csis.myclimateservice.eu/study/185/step/5120/view/data
2020-07-13 16:15
Firefox 78.0.1 (64-Bit) / Windows 10

![grafik](https://user-images.githubusercontent.com/18684786/87316245-d2d72b80-c525-11ea-8072-c227cc193c52.png)

I'll just stick with the proposed structure of these posts even though it looks a little bit funny with these short remarks :)

**expected behaviour:**: I would expect text without html tags.
**actual behaviour**: I do see html tags.
**steps to reproduce**: I selected Hazard Characterization - Local Effects and there the sub item "Data". All data packages (local effect apparent temperature, local effect mean radiant temperature and local effect UTCI temperature) have html tags. In their description.

_Originally posted by @johanneshorak in https://github.com/clarity-h2020/csis-technical-validation/issues/76#issuecomment-657598885_

**Comment by patrickkaleta** [comment]
Fixed for the Resource in question (description text was in the "wrong" description field, which didn't allow HTML tags), but this cannot be fixed in general for all Resources.

Original description field (called "DEPRECATED Description") only allows simple, unformatted text. We had to add a new description field ("Description (formatted)"), which allowed the use of HTML tags. If editors need to use HTML tags in their descriptions, they need to use the new description field and copy & paste the content from the old description field.
