### ISSUE TITLE
Data Package Content Type

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#19]
Create the Data Package Content type and the Links to External System (meta-data storage, e.g. [ckan](https://ckan.myclimateservice.eu/))
It has to contain all fields that allow for filtering and related Taxonomies for Hazard, Exposure, etc.

See also [CLARITY Data Package: Adaptation Options Resource specification](https://github.com/clarity-h2020/csis/issues/19)

**Comment by fgeyer16** [comment]
Since we have decided to use drupal for managing the metadata I have created two content types which are very basic at the moment:

1.Data Package:
  For now it only contains a field for a Description and a Reference Field to the second content type 
"dataset". For each metadata classifying the data package itself a field should be added to this content type.
2.Dataset:
This content type only contains the "Meta data target" field for now. This field is a reference to one of the terms of the EU-GL Vocabulary. Metadata classifying the dataset should be added as field to this content type. If datasets of different types need different metadata we can manage the display of the fields with the conditional fields module or form modes. So when somebody is creating the dataset he/she only will see the relevant fields which are needed for describing this dataset type.

**Comment by p-a-s-c-a-l** [comment]
Please refer to the [current draft of the CSIS Data Package Specification](https://docs.google.com/spreadsheets/d/10ii3Exq3SSkz5nmiUwRenumnhfw1h13_M5_FcKFha7Y/edit?usp=sharing).

The Specification shall be implemented as Content Type and for the serialisation into JSON we use the Drupal ~REST API~ [JSON:API](https://github.com/clarity-h2020/docker-drupal/issues/43).

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16 @patrickkaleta 

Is there any possibility to change the length of the *extent* field of the *Dataset* type? Max. length is 10, but that's not enough for e.g. '-180.0, -90.0, 180.0, 90.0':

*"The spatial_extent property defines the minimum bounding rectangle (xmin, ymin and xmax, ymax) defined by coordinate pairs of the spatial data resource. All coordinates for the data source fall within this boundary. E.g., "extent": [-180.0, -90.0, 180.0, 90.0]"*

![grafik](https://user-images.githubusercontent.com/1788226/49716698-cbb6b000-fc54-11e8-86bb-7b377bd1d1d9.png)

I think it would furthermore make more sense to define this as a spatial field so that we can make a spatial query: When the user wants to select a data package, only those data packages whose datasets (data resources) enclose the *study area* geometry shall be selectable.

**Comment by fgeyer16** [comment]
The only way to alter the length of a field, if there are already data in the database is to create a new field with the new specs. transfer the values and delete the old field. 
Since you want another representation of the data this should be the way any way.
I suggest to use a geofield with the bounding box widget.

**Comment by p-a-s-c-a-l** [comment]
Please update the various Data Package Content Types according to the [updated Data Package Specification](https://github.com/clarity-h2020/data-package/issues/9#issuecomment-454011194).

**Comment by fgeyer16** [comment]
The data package content type and the related content types are updated now.
@maesbri: Please check if everything is how intended.
