### ISSUE TITLE
Cannot delete Field

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#29]
@patrickkaleta @fgeyer16 
How can we delete a [faulty](https://github.com/clarity-h2020/docker-drupal/issues/28) / no longer used field? The [following instructions](https://drupal.stackexchange.com/a/110361) don't work with Drush 9.x: `Error: Call to undefined function field_delete_field() in eval() (line 1 of /app/vendor/drush/drush/src/Commands/core/PhpCommands.php(28) : eval()&#039;d code).`

**Comment by fgeyer16** [comment]
If the field is created by a module and drupal is fully aware of the field I do not know another way than the way you used [in the json_fiel issued](https://github.com/clarity-h2020/docker-drupal/issues/28).
Remove all instances of the field type and remove the module.
If you only want to remove one field, removing all instances of the field schould work. 
If an installation fails or the field is broken due to another reason and drupal does not show the field existent I fear trying to purge the field_name from the Database manually is the only way.
