### ISSUE TITLE
UndefinedLinkTemplateException

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#31]
Accessing the group admin page ( `/admin/group/`) sometimes yields to an UndefinedLinkTemplateException:

``
Drupal\Core\Entity\Exception\UndefinedLinkTemplateException: No link template 'edit-form.area' found for the 'group' entity type in Drupal\Core\Entity\Entity->toUrl() (line 224 of /app/web/core/lib/Drupal/Core/Entity/Entity.php)
``

The error is probably related to [this issue](https://www.drupal.org/project/groupmenu/issues/2880714).

**Comment by fgeyer16** [comment]
On the csis or on your local environment? If on local environment please check if in modules/contrib/group/src/Entity/Group.php in the annotations (the comment "defines group entity") in the form={} section 
>"default" = "Drupal\group\Entity\Form\GroupForm" 

is defined.

Otherwise we need to track down when "sometimes" is, what the circumstances are when the error occurs (coming from certain page, ...)

**Comment by p-a-s-c-a-l** [comment]
Problem probably caused by a '[damaged group entity](https://github.com/clarity-h2020/docker-drupal/issues/30#issuecomment-436526151)'. Disappeared after deleting/recreating the entity.
