### ISSUE TITLE
JSON:API vs. core's REST Module

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#43]
According to [this guide](https://www.drupal.org/docs/8/modules/jsonapi/fetching-resources-get), it should be possible to access [this node](https://csis.myclimateservice.eu/node/76) using Drupal 8's **JSON:API** via the following URI: https://csis.myclimateservice.eu/jsonapi/node/data-package/76

However, 404 Page not found is returned. Accessing the same node via the **REST module** does work: https://csis.myclimateservice.eu/node/76?_format=json

According to  [JSON:API vs. core's REST Module](https://www.drupal.org/docs/8/modules/jsonapi/jsonapi-vs-cores-rest-module), the JSON:API should be the preferred method for accessing entities.

@fgeyer16 @patrickkaleta Could you please check why the JSON:API isn't working?
@therter Could you please make sure that the [Map Component](https://github.com/clarity-h2020/map-component) uses the JSON:API?

**Comment by fgeyer16** [comment]
The JSON:API is working properly. there is/was only a misinterpretation of the [documentation](https://www.drupal.org/docs/8/modules/jsonapi/fetching-resources-get)  it says:
`http://example.com/jsonapi/node/article/{{article_uuid}}`
The "76" in your example is only the **node-id but not the UUID** (which is 2f9ec849-f8c4-4eb8-870d-f7e6c9423274 for now). 
I was not aware of this and needed myself now 1 1/2 hours to find this out. Even though it should have been clear for me at once if I had read the doc more precisely :-/.

**To get a node by its nid you have to use the [filtering capabilities](https://www.drupal.org/docs/8/modules/jsonapi/filtering) of the json api**:
`/jsonapi/node/data_package?filter[nid][condition][path]=nid&filter[nid][condition][operator]=%3D&filter[nid][condition][value]=76`
for nid 76

As a sort of explanation.
Since drupal stores the revisions of a node every revision gets an own uuid and the nid is pointing to the last revision of the node (as far as I understand it). By using the uuid the jsonapi is able to fetch revisions of the node and not only the current node content.

**Comment by p-a-s-c-a-l** [comment]
OK, great. So the [csis-helpers-module](https://github.com/clarity-h2020/csis-helpers-module]) should be extended to retrieve also the uuid.

In the meantime we can use the filter capabilities but should be aware, that the awkward syntax may trigger some false positive security alerts:

![grafik](https://user-images.githubusercontent.com/1788226/49012001-5806a480-f178-11e8-91a7-fb8c7fa8d58a.png)

**Comment by p-a-s-c-a-l** [comment]
resolved
