### ISSUE TITLE
"Include in Report Button" for external Apps

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#46]
As described in this [issue](https://github.com/clarity-h2020/docker-drupal/issues/20#issuecomment-446572012), we have to extend [ReactMount](https://csis.myclimateservice.eu/admin/structure/types/manage/react_mount_with_js/) and [iFrame](https://csis.myclimateservice.eu/admin/structure/types/manage/extended_iframe/fields) Content Types by  an "Include in report" button that uses [html2canvas](https://github.com/niklasvh/html2canvas) to create a screenshot of the whole embedded app (e.g. [map component](https://github.com/clarity-h2020/map-component) with all layers as shown on the screen, [table component](https://github.com/clarity-h2020/table-components) or [scenario-analysis component](https://github.com/clarity-h2020/scenario-analysis)) and stores it in the GL-Step.

We could either add [html2canvas.min.js](https://html2canvas.hertzen.com/dist/html2canvas.min.js) to [csis.libraries.yml](https://github.com/clarity-h2020/csis-theme/blob/dev/csis.libraries.yml) in [csis-theme](https://github.com/clarity-h2020/csis-theme/) and add a `<button>` + the respective REST calls to the Drupal API directly in an HTML field. Or we integrate the functionality ([JS function](https://github.com/clarity-h2020/scenario-analysis/blob/dev/app/scripts/controllers/mainController.js#L170)) in the [csis-helpers-module](https://github.com/clarity-h2020/csis-helpers-module). 

In any case, the "Include in Report Button" needs to be parametrised with the following contextual information:
- id of the html element that should be 'snap-shotted' by html2canvas
- target node and field where the snapshot (HTML Canvas serialised as image/png) should be stored (via JSON/REST API)

**Comment by fgeyer16** [comment]
> We could either add [html2canvas.min.js](https://html2canvas.hertzen.com/dist/html2canvas.min.js) to [csis.libraries.yml](https://github.com/clarity-h2020/csis-theme/blob/dev/csis.libraries.yml) in [csis-theme](https://github.com/clarity-h2020/csis-theme/) and add a `<button>` + the respective REST calls to the Drupal API directly in an HTML field. Or we integrate the functionality ([JS function](https://github.com/clarity-h2020/scenario-analysis/blob/dev/app/scripts/controllers/mainController.js#L170)) in the [csis-helpers-module](https://github.com/clarity-h2020/csis-helpers-module).

This has to be included in csis-helper module. Modules are for functionality themes for looking nice :-)
Maybe this should be a small separate module. 

May be I missed something on glimpsing on html2canvas. But how do we get an Imagefile from that to upload to the server?

**Comment by p-a-s-c-a-l** [comment]
> May be I missed something on glimpsing on html2canvas. But how do we get an Imagefile from that to upload to the server?

Here is an example: https://github.com/clarity-h2020/scenario-analysis/blob/dev/app/scripts/controllers/mainController.js#L170

`document.body.appendChild(canvas);` is just for testing purposes. It should be commented out.
` var imageBlob = canvas.toDataURL().replace(/^data:image\/(png|jpg);base64,/, '');` will get the image data from the canvas that was created by html2canvas from the html element identified by `elementId`

See also https://html2canvas.hertzen.com/

**Comment by fgeyer16** [comment]
Ah thank you.

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16 Any progress, plans, suggestions, ... here :-)

Is this the 'Snapshot' Field?

**Comment by p-a-s-c-a-l** [comment]
@patrickkaleta @fgeyer16 
FYI: Complete example for taking screenshots and posting to Drupal API is available in [drupalService.js](https://github.com/clarity-h2020/scenario-analysis/blob/dev/app/scripts/services/drupalService.js#L422)

**Comment by patrickkaleta** [comment]
Screenshots of maps and table are now being stored as Report images, which are linked to the corresponding GL-Step and can be viewed in the Summary tab and printed out in the report.

@p-a-s-c-a-l 
FYI: I mainly followed your approach (thanks for providing the link) and managed to implement it in "plain" JavaScript. 
Instead of sending a GET request for the GL-Step and later PATCHing that same GL-Step with the new Report Image, I'm sending another POST request in the end against the relationship endpoint for the Report Images array of the GL-Step. (more on this [here](https://www.drupal.org/project/jsonapi/issues/3017711#comment-12881674))

**So the whole approach looks like this:**
1) POST new file of the screenshot (same as your approach)
2) POST new Report Image including the UUID of the new file retrieved in 1) (same as your approach)
3) POST new Relationship for the respective GL-Step, payload only contains the entity type and UUID of the Report image (the GL-Step and the type of the relationship is already part of the URL)

**Comment by patrickkaleta** [comment]
I wouldn't close this issue just yet, since @DenoBeno suggested that we show to the user an Edit-form, where he/she can enter a description for the Report image, when they click on the "Include in Report" Button.
**Reason:** They can edit the description of a Report image on the Summary-Tab, but once they get to that tab, they might've already forgotten what this screenshot was really about.
**Problem:** We cannot show an Edit form for the Report Image directly, since this Report image doesn't exist until after the user clicks that button.
@fgeyer16 might've come up with a possible solution to this, so I will talk to him and try to implement it

**Comment by p-a-s-c-a-l** [comment]
Any progress to report here?

**Comment by patrickkaleta** [comment]
Already done. Suggestions by @DenoBeno have been implemented. I forgot to update & close the issue.

**Comment by p-a-s-c-a-l** [comment]
The Button does not work for the [Study Area Map](https://csis.myclimateservice.eu/study/1/view/area).

**Comment by p-a-s-c-a-l** [comment]
See https://github.com/clarity-h2020/csis-helpers-module/issues/9
