### ISSUE TITLE
Solution Offer URL alias not working

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#70]
Users are forced to provide an URL alias after having created a new Solution Offer:

![grafik](https://user-images.githubusercontent.com/1788226/58099769-9a1b1b00-7bdc-11e9-809c-1d557d39a8fe.png)

However, the entered alias is not working: https://csis.myclimateservice.eu/solution-offers/my-great-solution-offer

So either we disable the alias creation form (how?) or we fix this issue.

**Comment by patrickkaleta** [comment]
> Users are forced to provide an URL alias after having created a new Solution Offer:
> 
> ![grafik](https://user-images.githubusercontent.com/1788226/58099769-9a1b1b00-7bdc-11e9-809c-1d557d39a8fe.png)
> 
> However, the entered alias is not working: https://csis.myclimateservice.eu/solution-offers/my-great-solution-offer
> 
> So either we disable the alias creation form (how?) or we fix this issue.

There seems to be something broken with the Group module (which is responsible for this form you see) and the generation of URL aliases. The form you see is for filling out your membership details (so IMO an URL alias field makes no sense here at all). And since we haven't added any fields to Group member, you don't see anything besides the URL alias field.

My suggestion is to (after ECCA) disable this form by unchecking the "Group creator must complete their membership" field in the [Solution offer Group settings](https://csis.myclimateservice.eu/admin/group/types/manage/solution_offer) and create an automatic URL alias for Solution offers [here](https://csis.myclimateservice.eu/admin/config/search/path/patterns) (e.g. like this: `/solution-offer/[group:ID]`). This would then be identical to our approach for Studies.

Additionally, we could include the URL alias field in the first form (creating the actual Solution offer), where the user could choose to overwrite the automatic pattern described above and enter a custom URL if he likes. But then we could potentially  lose the GroupID from the URL context, so we wouldn't be able to use it in Views for filtering or other operations. 
@fgeyer16 WDYT: should it possible to enter custom URLs or could that have too many drawbacks for us?

**Comment by fgeyer16** [comment]
> My suggestion is to (after ECCA) disable this form by unchecking the "Group creator must complete their membership" field in the Solution offer Group settings and create an automatic URL alias for Solution offers here (e.g. like this: /solution-offer/[group:ID]). This would then be identical to our approach for Studies.

I think we do not need to disable the step. We only need to remove the url-alias [here](https://csis.myclimateservice.eu/admin/group/content/manage/solution_offer-group_membership/form-display)

> @fgeyer16 WDYT: should it possible to enter custom URLs or could that have too many drawbacks for us?

I think the user has to fill a lot field and this url alias thing can may be confuse him. The user also has to enter the complete url if we want coherent aliases ( and we want). So the user will always have to enter the full url (e.g. /solution-offers/his-alias). I doubt this will do everybody even if we make akclear description. So Ithink automatic url-aliases are the better choice. If we want something SPeaking in the url of a solution offer, we can do this in that way as well.

**Comment by patrickkaleta** [comment]
> I think we do not need to disable the step. We only need to remove the url-alias [here](https://csis.myclimateservice.eu/admin/group/content/manage/solution_offer-group_membership/form-display)
> 
I tried that on my local instance but the error still occured even after removing that field. 
<br>
> > @fgeyer16 WDYT: should it possible to enter custom URLs or could that have too many drawbacks for us?
> 
> I think the user has to fill a lot field and this url alias thing can may be confuse him. The user also has to enter the complete url if we want coherent aliases ( and we want). So the user will always have to enter the full url (e.g. /solution-offers/his-alias). I doubt this will do everybody even if we make akclear description. So Ithink automatic url-aliases are the better choice. If we want something SPeaking in the url of a solution offer, we can do this in that way as well.

I agree with using only automatic URL-aliases. We could append the title of the Solution offer after the ID to make the URL a bit more user-readable:`/solution-offers/[Offer-ID]/[Offer-Title]`, so e.g. ".../solution-offers/6/digital-heavy-rain-hazard-maps". Or we just stick to `/solution-offers/[Offer-ID]` (similiar to the aliases for Studies.)
@p-a-s-c-a-l: As one of our few solution owners, what do you think of that?

**Comment by p-a-s-c-a-l** [comment]
> I agree with using only automatic URL-aliases.  👍 

I support `/solution-offers/[Offer-ID]`

**Comment by patrickkaleta** [comment]
> > I agree with using only automatic URL-aliases.  👍
> 
> I support `/solution-offers/[Offer-ID]`

Done. I configured the automatic URL aliases for new solution offers and updated the already existing solution offers by hand.
