### ISSUE TITLE
Step-by-Step Wizard

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#72]
We have to implement the step-by-step wizard to guide the user through the process / EU-GL Steps.

There is already a "SAW Wizard" module in `/modules/custom/saw_wizard` (**not** in `web/modules/custom/saw_wizard`). 

@fgeyer16 What's the status here?

**Comment by p-a-s-c-a-l** [comment]
Is there a possibility to disable tabs based on some conditions? E.g. RA/IA and beyond should not be accessible until the user has [selected](https://github.com/clarity-h2020/docker-drupal/issues/58) the RPC/time period and only after impact calculation in EMIKAT is completed.

Furthermore, could we show the [Scenario Selection UI](https://github.com/clarity-h2020/docker-drupal/issues/58) when the user wants to switch from VA to RA/IA in the wizard? We could also introduce a new sub-tab "Scenario" in RA/IA that lets the user visualise / change information on the baseline (selected events) and adaptation scenario (selected adaptation options).

**Comment by patrickkaleta** [comment]
> Is there a possibility to disable tabs based on some conditions? E.g. RA/IA and beyond should not be accessible until the user has [selected](https://github.com/clarity-h2020/docker-drupal/issues/58) the RPC/time period and only after impact calculation in EMIKAT is completed.
> 
A while back I added the [Progress indicator field](https://csis.myclimateservice.eu/admin/group/types/manage/study/fields/group.study.field_progress_indicator) to Studies. It represents how far the study has advanced and the view responsible for the study menu activates or disables the steps based on that field (e.g. Progress indicator = 3 would mean that for the first 3 EU-GL steps the links would be active, all others would be disabled.
Currently, since the conditions are not clear yet, this field gets incremented once the user visits a tab in the currently most advanced step of the study for the first time. It is possible to check conditions (e.g. has a field value been set or changed? etc) & increase this indicator every time the study or a GL-step is changed. Also external components could increment this progress indicator via REST call.

> Furthermore, could we show the [Scenario Selection UI](https://github.com/clarity-h2020/docker-drupal/issues/58) when the user wants to switch from VA to RA/IA in the wizard? We could also introduce a new sub-tab "Scenario" in RA/IA that lets the user visualise / change information on the baseline (selected events) and adaptation scenario (selected adaptation options).

We could make selecting a RCP & time period one condition to advance to the next steps of the study to "trap" the users in the HC or HC-LE step until they make that decision. In the RA/IA step we would then show them what they chose.

**Comment by p-a-s-c-a-l** [comment]
Perhaps we could go for something really simple as used in the [Marketplace](https://marketplace-dev.myclimateservices.eu/offers/add)?

![grafik](https://user-images.githubusercontent.com/1788226/74836409-a5dc6f00-531f-11ea-9d72-bc5088fd3f87.png)

**Comment by patrickkaleta** [comment]
@fgeyer16 WDYT? Would it be possible?

**Comment by fgeyer16** [comment]
This really simple thing comes from the forms_steps module so if we want to habe this issue: #136 .
Is this about editing or viewing?

**Comment by p-a-s-c-a-l** [comment]
> Perhaps we could go for something really simple as used in the [Marketplace](https://marketplace-dev.myclimateservices.eu/offers/add)?

Unfortunately, now this doesn't seem enough as [fundamental usability issues](https://github.com/clarity-h2020/docker-drupal/issues/141#issuecomment-590354829) have to be addressed asap. So if it is easily possible to disable steps based on a condition (no country selected yet, EMIKAT calculation not finished yet, ...), we should do it. If not, we have to find another pragmatic solution for these usability issues.
