### ISSUE TITLE
Improve PDF Output of Reports

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#74]
PDF Output of Report Generation doesn't look very nice.

*Configure additional PDF Views, e.g. for Taxonomy Terms and Report Images. There also a possibility to style PDF with custom CSS.* See https://github.com/clarity-h2020/docker-drupal/issues/20#issuecomment-473309782

The [final Report] has to include a a frontage, disclaimer, etc.

**Comment by patrickkaleta** [comment]
Sadly it seems like there has been a setback in the meantime. As shown in [this comment](https://github.com/clarity-h2020/docker-drupal/issues/20#issuecomment-473309782) it was already possible to print a PDF with images. This is currently not working anymore - each time there is an image, report generation fails with the following error:
`Error generating document: Failed to generate PDF: file_get_contents(https://csis.myclimateservice.eu/sites/default/files/styles/max_325x325/public/report-images/2019-05/map-snapshot_10.png?itok=Ie2KPDOU): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error , Image not found /sites/default/files/styles/max_325x325/public/report-images/2019-05/map-snapshot_10.png?itok=Ie2KPDOU,... `

Visiting one of the shown [URLs](https://csis.myclimateservice.eu/sites/default/files/styles/max_325x325/public/report-images/2019-05/map-snapshot_10.png?itok=Ie2KPDOU) only returns a `Error generating image` message and in the [Drupal logs](https://csis.myclimateservice.eu/admin/reports/dblog) 3 events are logged ([1](https://csis.myclimateservice.eu/admin/reports/dblog/event/1946763), [2](https://csis.myclimateservice.eu/admin/reports/dblog/event/1946764), [3](https://csis.myclimateservice.eu/admin/reports/dblog/event/1946765)).

Viewing the PDF in Entity Print's debug mode ([link](https://csis.myclimateservice.eu/print/pdf/node/22/debug)) works and images are shown as expected.

Not sure what exactly causes this problem, but based on the error messages I'm assuming it's related to #109

**Comment by patrickkaleta** [comment]
Indeed it is again a problem with the file permissions on the server.

It looks like the **styles** folder and its subfolders (`/app/web/sites/default/files/styles`) need different permissions. Most of the folders have `docker` set as **owner-user** and **owner-group**, that doesn't seem to work well. For now, I set `www-data` as the **owner-user** for the `max_325x325` folder and its subfolders (since for this folder the errors above where shown) and I will check if those changes in permission will now cause problems in other places.

Report generation now working again for e.g. this [GL-step](https://csis.myclimateservice.eu/study/1/step/22/view/summary).

**Comment by patrickkaleta** [comment]
### Steps to do in order to improve PDF output:

- [x] 1. place the "View PDF" field in all entity displays, where we want to generate PDFs

- [x] 2. activate the PDF view mode for those entities and configure them

- [x] 3. add custom CSS to theme for styling the PDFs

- [x] (additionally) 4. create custom Twig templates for further modifying HTML output of Reports

**Note:**
For debugging purposes, Entity print offers a debug view, which allows to view the "PDF" withou actually creating it. For that one just has to append a **"/debug"** to the URL that would normally create the PDF.
E.g.:  https://csis.myclimateservice.eu/print/pdf/node/22/debug or https://csis.myclimateservice.eu/print/pdf/group/1/debug

**Comment by patrickkaleta** [comment]
### Ad 1. "View PDF" fields

Entity Print comes with a special field, that creates the link for the PDF generation. This should be placed in those entity displays, where we want to offer PDFs. For now, this will be the case for the `Study` group and the `GL-step` node (for both in the "Summary" display mode).

Additionally, someone created a Display Suite token field, that does exactly the same as the mentioned field above. IMO we should use the field provided by Entity Print and not create a custom one with the exact same functionality. I added a "DONT USE" to the label of the Display Suite token. In the future we could completely remove this.

**Comment by patrickkaleta** [comment]
### Ad 2. "create PDF view modes"
By default Entity print will create the PDF based on what's shown on the `Default` view mode of the entity. To furher specify which fields should be shown in the PDF, once just needs to create a new view mode for each entity type with a machine name equal to `pdf`.

I've done that for GL-step and Study, which should be enough for now. I based those view modes on the respective `Summary` view modes of those entities.

**Comment by patrickkaleta** [comment]
### Ad 3. "add custom CSS to theme"

To add custom CSS it should be enough to follow the simple steps provided in the Entity print [description](https://www.drupal.org/docs/8/modules/entity-print/usage#from-your-theme).

For that I created a new [branch](https://github.com/clarity-h2020/clarity-theme/tree/feature/010-pdf-styling) and separate [issue](https://github.com/clarity-h2020/clarity-theme/issues/10).

**Comment by DenoBeno** [comment]
I have updated the ownership & rights on all directories and files under /files, as explained in https://github.com/clarity-h2020/docker-drupal/issues/109#issuecomment-533671632

If you have any new problems now, please yell.

**Comment by DenoBeno** [comment]
I have configured an initial version of the "full report". It works relatively OK in "debug" mode, but PDF generation is too slow.

preview: https://csis.myclimateservice.eu/print/pdf/group/1/debug

PDF generation: `Fatal error: Maximum execution time of 30 seconds exceeded in /app/vendor/dompdf/dompdf/src/Frame.php on line 331`

DomPDF is supposed to be replaced ASAP anyway, so I'm not going to start improving this now. See https://csis.myclimateservice.eu/admin/config/content/entityprint

**Comment by DenoBeno** [comment]
"Edit image comment" button should be disabled by CSS in PDF print.

**Comment by patrickkaleta** [comment]
> I have configured an initial version of the "full report". It works relatively OK in "debug" mode, but PDF generation is too slow.
> 
> preview: https://csis.myclimateservice.eu/print/pdf/group/1/debug
> 
> PDF generation: `Fatal error: Maximum execution time of 30 seconds exceeded in /app/vendor/dompdf/dompdf/src/Frame.php on line 331`

That's what I was worried about. Those reports can get pretty long with lots and lots of pictures. I'm not sure if another PDF engine will fix that.

> 
> DomPDF is supposed to be replaced ASAP anyway, so I'm not going to start improving this now. See https://csis.myclimateservice.eu/admin/config/content/entityprint

Locally I managed to get the [WKhtmltopdf](https://wkhtmltopdf.org/) engine working (my mistake was to include the binaries for the Ubuntu version, until I realized that we have Debian running in the Docker container...). However, the current 0.12.5 version doesn't generate a table of contents ([bug report](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3953)) and I was unable to install the previous 0.12.4 version.
@DenoBeno I still haven't heard from the guys at ATOS who are responsible for setting this up in the DRIVER project. What version are they running? Can you please talk to them directly?

**Comment by patrickkaleta** [comment]
> "Edit image comment" button should be disabled by CSS in PDF print.

I added that as an requirement for the PDF CSS-styles.

**Comment by DenoBeno** [comment]
Apparently, we should install it with composer. https://www.drupal.org/docs/8/modules/entity-print/pdf-engine-support

composer require h4cc/wkhtmltopdf-amd64 (or i386)
composer require mikehaertl/phpwkhtmltopdf

**Comment by p-a-s-c-a-l** [comment]
> composer require h4cc/wkhtmltopdf-amd64 (or i386)
> composer require mikehaertl/phpwkhtmltopdf

ok, done

**Comment by DenoBeno** [comment]
OK. Had to bring the system up to date and install a few additional libraries but PDF generation works now. For the record: 

apt-get update
apt-get upgrade
apt-get install libxrender1 libfreetype libssl1.0-dev

Result: we can produce PDFs with TOC now. Should still be made nicer, but it works in principle. See e.g.:

[Adaptation Scenarios for Metropolitan Resilience Planning (1).pdf](https://github.com/clarity-h2020/docker-drupal/files/3669437/Adaptation.Scenarios.for.Metropolitan.Resilience.Planning.1.pdf)

**Comment by DenoBeno** [comment]
I will not have time to improve the PDF formatting, someone else needs to pick this up now.

**Comment by patrickkaleta** [comment]
> I will not have time to improve the PDF formatting, someone else needs to pick this up now.

I want to contribute and create the necessary styling for the PDF, but I'm still waiting for @bullz to reply to my email, since I need his help to configure a separate CSS file inside our theme.

**Comment by patrickkaleta** [comment]
> > I will not have time to improve the PDF formatting, someone else needs to pick this up now.
> 
> I want to contribute and create the necessary styling for the PDF, but I'm still waiting for @bullz to reply to my email, since I need his help to configure a separate CSS file inside our theme.

Ok, I was just informed that @bullz did reply but somehow the mail got lost. I should now be able to add a separate styling to the PDFs.

**Comment by patrickkaleta** [comment]
The overall structure (order of heading levels, define what will be a heading,...) of the PDF report should be ok now. This is important, because the TOC is generated automatically by extracting all available headings in the document. I followed @DenoBeno [advice](https://github.com/clarity-h2020/docker-drupal/issues/77#issuecomment-537838827) mentioned in #77. I decided to create dedicated **PDF** view modes for each content type or taxonomy used in the final report, so that we have a clean separation between what's going to be shown on the website and what's going to be shown in the PDF report. 

It's up to discussion, what should be included in the TOC. If we want (for example) to have each resource of the selected data package diplayed in the TOC or not (ATM that's the case, because the title of each resource is rendered as a `h6`. However, this caused the TOC to be 2 pages long). If we want to hide some elements from the TOC, but still have them displayed inside the document as a header, I suggest replacing the header element in the content type's **display mode** with a `span` and adding a special css-class (e.g. "h1", "h2", "h3",...) to it. (That might not be good practice from a HTML standpoint, but since all of this will **only** be shown in the PDF, it does not matter.)

Up next I will focus on the CSS and try to add page numbering to the PDF as well.

**Comment by patrickkaleta** [comment]
> Up next I will focus on the CSS and try to add page numbering to the PDF as well.

Generating the page numbers turned out to be more difficult than anticipated, so I'm skipping that for now. The CSS for our customized PDF reports is done (done for now, of course we will further improve this in the future).

**Some notes/problems:**
- I defined two custom CSS classes:
  - `hide-in-print`: hides the element in the final PDF (used for "Edit report image" buttons)
  - `print-break`: ensures that this element is placed on a new page (used for main sections of the document)

**Usage: (probably most useful for @DenoBeno)** let's says you find something on the report that you would rather not see there, then you simply have to find where this element is generated (could be a view or a field in the view mode) and then you add the CSS class hide-in-print (so like that: <your-element **class="hide-in-print"**....>).

- I tried to implement a similiar CSS class that would prevent items to be printed on separate pages (e.g. forbid that the title of a report image ends on one page and the actual image then appears on the next page). However, this seems to be more complicated to achieve in CSS, so I had no luck so far.
- I've added a serif font in the CSS and it is shown in the debug mode, but when I download the document it doesn't use the serif font. I don't know why this CSS rule is ignored when all the others are working
- another strange thing happens with very long headings (like it's the case for resources). They are smashed together in the same line instead of being splitted into multiple lines. I've never seen this and I don't know how this can be fixed. 
@bullz please have a look at this, maybe you know how to fix that.

**Comment by bullz** [comment]
I can't see why this happens, and in my local system I have an error when creating PDF.

But I would try this two things:

1. Remove every PDF css and see if it still occurs
2. Change site theme to Drupal default and generate another PDF

![pdf](https://user-images.githubusercontent.com/160349/67395002-7ef67200-f5a5-11e9-9da0-69162bdd0417.png)

**Comment by patrickkaleta** [comment]
> I can't see why this happens, and in my local system I have an error when creating PDF.
> 
> But I would try this two things:
> 
> 1. Remove every PDF css and see if it still occurs
> 2. Change site theme to Drupal default and generate another PDF

You're right, I'm also getting errors in my local environment. Not sure, what's going on there. I will look into it once the "high priority" issues have been resolved.

**Comment by DenoBeno** [comment]
Is this still an issue?

**Comment by patrickkaleta** [comment]
> Is this still an issue?

This is still very much an issue. Just like @bullz I'm getting several errors ("cannot open librender library", "cannot resolve SSLv3" errors, etc.) when I try do generate a PDF in my local environment. 

I'm using the newest build of our CSIS, so I'm sure whether this hasn't been installed/configured correctly in the docker container on our server, or if it's because of the fact that it's just a localhost.

Using wkhtmltopdf version 0.12.5 solves those issues for me locally, however **updating is not an option** since 0.12.5 has a known bug which makes it impossible to generate a TOC (which was the reason we decided to use wkhtmltopdf in the first place). And so far there is no newer version of this module ☹️ 

... so I can work on improving the CSS of the reports locally, but I can only test it on our dev-server. Not very efficient, but probably our best option ATM. Will get back on it once the main issues around Emikat and our new Study type have been solved.

**Comment by patrickkaleta** [comment]
### FYI:

I had a bit of time to get back to this issue, but I noticed, that the report generation is currently not working on the dev server:
![print-error](https://user-images.githubusercontent.com/42167036/69728241-6d643500-1124-11ea-9530-c65915d971b9.png)

To find the missing libraries I followed [these instructions](https://www.cyberciti.biz/faq/debian-ubuntu-linux-wkhtmltopdf-error-while-loading-shared-libraries-libxrender-so-1/), which also explains how to install the missing libraries, but I'm guessing it can't be used 1:1 inside a Docker container.

@DenoBeno already installed those missing libraries a while back ([commented here](https://github.com/clarity-h2020/docker-drupal/issues/74#issuecomment-536446853)), but I suppose after the recent Docker container update those changes got lost. 
@p-a-s-c-a-l  (& @DenoBeno ) how should be proceed here to get those libraries back?

**Comment by p-a-s-c-a-l** [comment]
I'll update the docker image and include `libxrender1` `libfreetype` and `libssl1.0-dev`.

**Comment by p-a-s-c-a-l** [comment]
I've added the libraries libxrender1, libfreetype**6** and libssl1.0-dev to the [docker image](https://github.com/clarity-h2020/docker-drupal/issues/130) and recreated the containers. PDF generation is still not working:

`Error generating document: Failed to generate PDF: /app/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory 
`

**Comment by p-a-s-c-a-l** [comment]
Problem [solved](https://github.com/clarity-h2020/docker-drupal/issues/130#issuecomment-564115396). 

[The report](https://github.com/clarity-h2020/docker-drupal/files/3945967/Advanced.Screening.Alba.Iulia.pdf) doesn't look that bad apart from some visual glitches:

![grafik](https://user-images.githubusercontent.com/1788226/70548465-d8752900-1b72-11ea-80c3-42bc28801322.png)

Maybe the title is just too long and no line break is inserted?

**Comment by p-a-s-c-a-l** [comment]
good enough
