### ISSUE TITLE
Update Data Package Views

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#75]
Update Data Package Views to use new the Tags Array instead of the  EU-GL Context object of the Data Package Resource.

See https://github.com/clarity-h2020/data-package/issues/14#issuecomment-506244759

**Comment by fgeyer16** [comment]
I will have to rethinke things, so this will need some time

**Comment by p-a-s-c-a-l** [comment]
> I will have to rethinke things, so this will need some time

How much time? It's a SHOWSTOPPER issue. Do you need support?

**Comment by fgeyer16** [comment]
Was easier than I thought first. So the view is now updated to use the tag field.
But it seems, that the tag field is not filled with all values for the resources.

**Comment by p-a-s-c-a-l** [comment]
Thanks. Can you reproduce this strange behaviour when selecting taxonomy terms:
 ![taxonomies](https://user-images.githubusercontent.com/1788226/60430772-6a5d2b00-9bfe-11e9-9269-3649fc25f9c7.gif)

If causes Firefox to consume 100% CPU. Looks like an endless in the selection.

Furthermore, where do I find this / display view:
![grafik](https://user-images.githubusercontent.com/1788226/60430934-ce7fef00-9bfe-11e9-9ce4-1dab48f3b10c.png)

I want to add show fields that are currently hidden.

**Comment by fgeyer16** [comment]
I neither did I see this behavior on chrome nor on FF. But I checked js and maybe there was a problem with bubbling of the click event. I think this is fixed now. Please try it since i did not see this.

the display of the resource you will find here: https://csis.myclimateservice.eu/admin/structure/views/view/rest_node/edit/rest_export_3. The whole html is in the "display" field at the bottom of the fields list.

**Comment by p-a-s-c-a-l** [comment]
works now
