### ISSUE TITLE
Final Report

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#77]
Create a new view as last tab ("Report") that aggregates all summary views to present a final report that can be [exported as PDF](https://github.com/clarity-h2020/docker-drupal/issues/74).

**Comment by DenoBeno** [comment]
Well, it's easy to add a new step to the study now. Just add another template...

So this template would need to have what exactly in it? How are the summary views made in other templates today?

**Comment by DenoBeno** [comment]
I looked into this and the way GL-step "summary" is rendered is not appropriate for what we need in the final step.

IMO the best way to generate the complete document would be by defining a PDF display view of the group that includes the PDF display views of all the included GL steps. This can be done in different ways: with viewfield, with EVA, or with a view that prints the group in the header and then all the group nodes in the loop.

I'll implement an EVA for the printout and another one for showing the data on the wen page (not sure if we need both), then we can talk further...

**Comment by DenoBeno** [comment]
I made a first attempt at this, see https://csis.myclimateservice.eu/admin/structure/views/view/study_print_eva?destination=/admin/structure/views

It should work, but it doesn't, not sure why.

See 
https://csis.myclimateservice.eu/study/17/view/summary
https://csis.myclimateservice.eu/print/pdf/group/17/debug
https://csis.myclimateservice.eu/print/pdf/group/17

**Comment by DenoBeno** [comment]
The summary view of the group now shows also the summaries of the individual steps. I'll further improve the output before going to fix the PDF export in the same way.

Where we want to show this is another question. Since the view already exists, the simplest way of achieving the result might be by linking the group summary page from other summary pages. What pascal has asked for would be more difficult to do...

Here is what happens if I add an empty GL-step node to a report and call it "report"

![image](https://user-images.githubusercontent.com/2961790/65580653-5ebd9e00-df7a-11e9-9316-cde6f83eed1b.png)

Unfortunately, the "Introduction", "Data" and "Summary" tabs are produced in a different way than other tabs, so we can't so easily remove or replace them. But it's definitely possible to do it. 

This is how the table view is defined in GL-step:
![image](https://user-images.githubusercontent.com/2961790/65581128-397d5f80-df7b-11e9-8721-eaf22a1ba5a7.png)


And this is how the summary step view is:
![image](https://user-images.githubusercontent.com/2961790/65581268-747f9300-df7b-11e9-85c0-05a9cfd6b3cc.png)

Obviously, we can't replace the contents of the summary step view as easily as we can replace the contents of the table view... This would have to be rewritten if we want to go that way....

Simpler way: just add a link to the summary page. I wasn't able to make it look like other buttons, so I uploaded an icon and use the img tag to show it. Here is a result:

![image](https://user-images.githubusercontent.com/2961790/65594728-a866b280-df93-11e9-8d81-0f9dddfa7ad2.png)

To change this, edit the footer in https://csis.myclimateservice.eu/admin/structure/views/view/study_group_main_navigation_v2/edit/block_2 view

**Comment by DenoBeno** [comment]
Obviously, the "print" icon could just as well be a pdf icon or "report" button. And it could immediately produce the PDF instead of changing the page...

**Comment by DenoBeno** [comment]
Some recommendations concerning the print output:

1. Use default view mode where it fits. If the view mode needs to be changed for printing, always define a PDF view mode.
2. Consider adding `<section>`  tag in addition to `<Hn>`. This is easy to do now, difficult to do later and it *could* help us to produce better CSS formatting down the road.
3. Remove dynamically generated content (applications) from print view. 
4. See https://github.com/clarity-h2020/clarity-theme/issues/7#issuecomment-537516564 for recomendations regardign the data views. Full data package resources list should IMO only be include as an annex document/lat chapter in the report.
5. We should IMO let EVAs produce the sub-section titles rather than adding fix sub-sections in the PDF view mode. Especially for the sections that will often be empty, like these:

![image](https://user-images.githubusercontent.com/2961790/66110156-82aa6080-e5c6-11e9-9632-244e642aa4d8.png)

**Comment by patrickkaleta** [comment]
I think we can close this now.  @DenoBeno created the button that creates the whole PDF document and linked it in the top navigation of the Study. I'm done now with the first version of the custom CSS for our PDF reports.
