### ISSUE TITLE
Twins cannot be removed from the study report

### ISSUE THREAD

**Issue by therter** [clarity-h2020/docker-drupal#81]
Twins, which are included in the study report cannot be removed from the report

![anim](https://user-images.githubusercontent.com/1788509/60831616-3f547780-a1ba-11e9-8407-1a30cf115e95.gif)

Error message from the console:

![Bildschirmfoto vom 2019-07-08 19-50-03](https://user-images.githubusercontent.com/1788509/60831626-45e2ef00-a1ba-11e9-8283-cd6319a6bf9c.png)

**Comment by patrickkaleta** [comment]
I found the problem! As can be seen in the screenshot, for this GL-step there was a missing element in its relationsships. JSON:API checks those relationsships before performing any POST,GET or DELETE requests and threw an error, since it found no match for a UUID = "missing". Problem is that Drupal doesn't remove any references of a content element when it's deleted, which leads to the "missing" value in the relationships field.
![missing-report-image-entity](https://user-images.githubusercontent.com/42167036/60886622-c5240180-a252-11e9-9522-24a52e698808.png)

This was discussed earlier but I couldn't find the corresponding issue. The solution was that we store the relationsship between GL-Step and Report image **only** in the Report image. The field [report_images](https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step/fields/node.gl_step.field_report_images) in the GL-Step should not be used anymore and can at some point be removed. 

I already made the appropriate changes in the "Include in report" functionality of the CSIS_helpers module, but I think @p-a-s-c-a-l has to do so as well for the Scenario analysis component (the final REST call updating the GL-step entity has become obsolete).

**Comment by DenoBeno** [comment]
Is this a Drupal bug? If yes, please report it in drupal.org.

Also, please post a "best practice" for working with JSON:API - we may need this information in the future.

**Comment by p-a-s-c-a-l** [comment]
wtf

**Comment by p-a-s-c-a-l** [comment]
Cannot remove entries: ![exposure-twins](https://user-images.githubusercontent.com/1788226/65686625-92292700-e065-11e9-9468-ee6798362320.gif)

Additionally, I don't understand why cids GUP (solution offer / showcase) appears in this list.

**Comment by patrickkaleta** [comment]
My first guess is that those two tables (Included & Available) are not generated properly. Looking at GL-step [1460](https://csis.myclimateservice.eu/node/1460/edit) (HC step of study 33) shows in the `Included data` field just one element. So, right now the system is trying to remove things that are not even part of that step. This is the updated version of the Twins tab, so I'm asking @DenoBeno to have a look at those views.

> Additionally, I don't understand why cids GUP (solution offer / showcase) appears in this list.

I assume you were in the HC step of the study? The [cids GUP showcase](https://csis.myclimateservice.eu/node/525/edit) has the **Hazard characterization** term assigned to it in the `workflow step` field, so at least that doesn't seem to be a bug.

**Comment by DenoBeno** [comment]
Interesting, I thought that was fixed. Will take a look at https://csis.myclimateservice.eu/study/33/step/1519/view/twins and fix it.

**Comment by DenoBeno** [comment]
OK, the reason was a misconfiguration of the template. Whenever a twin view is used, one MUST define the input variables as shown below.

![image](https://user-images.githubusercontent.com/2961790/65865707-09b3ca80-e374-11e9-8803-f04a784e58ba.png)

If the arguments aren't defined, bad things will happen.

Update: for the new hazards twin, just the node id parameter is needed and possibly not even that.

**Comment by DenoBeno** [comment]
I have fixed all the "twins" views for all the templates and also for existing studies. Can we close this now?
