### ISSUE TITLE
Anna Åkesson can not create an account in CSIS

### ISSUE THREAD

**Issue by LenaStr** [clarity-h2020/docker-drupal#97]
Anna Åkesson can not create an account in CSIS. The problem is that her e-mail seems to be used in an older version of an account that is not accessible.

**Comment by LenaStr** [comment]
Yeshewa also have a problem. E-mail: yeshewatesfa.hundecha@smhi.se

Error message says: Username has not been activated or is blocked

**Comment by LenaStr** [comment]
This is also very important for the demo on the 5th and we need acces at latest one week before in order to have time to prepare demos.

**Comment by fgeyer16** [comment]
I think Anna Åkesson can login now, the confirmation link was stuck in the mail filter of wsp.
Yeshewa is unblocked now as well

**Comment by patrickkaleta** [comment]
> Yeshewa is unblocked now as well

In addition, I made Yeshewa an "Editor" now. That should give her all needed permissions.

@LenaStr 
By default new user accounts are deactivated (due to fake accounts that are created by bots), so they first need to be activated by an administrator. So if anyone of our partners needs an account, it would be (at least at the moment) best to send an email as well to either @fgeyer16 or me.

@fgeyer16: could we implement some kind of feature that would automatically let us know of any newly created accounts? And ideally even give users an option to select the desired user role(s) that they want? All that of course without messing much with the already implemented single-sign-on CAS.

**Comment by DenoBeno** [comment]
I can't do anything about SSO, getting myself out of the loop

**Comment by patrickkaleta** [comment]
@LenaStr do you know if Anna is still experiencing any problems with the login? Can we close this issue?

**Comment by fgeyer16** [comment]
Anna manages to login now.
 so closing
