### ISSUE TITLE
patch business rules

### ISSUE THREAD

**Issue by fgeyer16** [clarity-h2020/docker-drupal#98]
Business rules needs another patch

https://www.drupal.org/files/issues/2019-03-29/view-result-loop-3043752-9.patch due to this issue. https://www.drupal.org/project/business_rules/issues/3043752

As I know from other projects automatically applying wont work so we have to do it manually.
(and maybe make afterwards a patch for our selves so we will not forget that again

**Comment by patrickkaleta** [comment]
@fgeyer16: Not sure, what exactly you meant by "do it manually", but I didn't want to directly edit a contributed module. **So I instead updated the mentioned patch file**. An additional `use statement` was added in the source file after the patch was originally created. And that's why the original patch couldn't be applied anymore using our [best practice](https://github.com/clarity-h2020/csis/issues/75) method.

**Patch is now active, however it still doesn't seem to solve our problem.** I followed the [step-by-step instructions](https://www.drupal.org/project/business_rules/issues/3043752#comment-13042915) in the issue to recreate the original problem and indeed, for that case applying the patch solved the issue even using business_rules beta8.

So, either our problem is not fully related to this issue or our business rule workflow is not configured correctly.

**Comment by DenoBeno** [comment]
I looked into the code & patch for a while now. This is what the patch should result in:

        if ($entity->uuid->getValue() !== $saved_uuid) {
          $key_value->set($uuid, $uuid);
		  if ($entity->isNew()){
            $entity->save();
          } else {
            $uuid_service = \Drupal::service('uuid');
            $uuid_new = $uuid_service->generate();
            if(Uuid::isValid($uuid_new) == TRUE){
              $entity->uuid->value = $uuid_new;
              $entity->nid->value = NULL;
              $entity->save();
            }
          }

That is: if something has changed the UUID value of the entity variable, assume that the entity should be saved as new. I have now instructed rules to assign a  random number token to UUID (hope there is no sanity check before this code) and tried to see what happens.

this is the action: https://csis.myclimateservice.eu/admin/config/workflow/business_rules/action/copy_template_to_study_step/edit#field_value-uuid

It is triggered in a loop whenever this group is saved: https://csis.myclimateservice.eu/group/17/edit

The result shoudl be TWO new GL nodes assigned to the group. (see https://csis.myclimateservice.eu/group/17/content)

At the moment, it's still just one. Has this patch been applied to the site or just locally on your machine?

**Comment by fgeyer16** [comment]
With do it manually I meant find the lines in question in a text editor and change them there. So yes this is direct editing a contributed module. For a patch with only 2 changes like this I would say this is save. the patch commend does nothing else.

I checked the file on the csis and it seems the patch was not applied. Added the changes directly now.

**Comment by DenoBeno** [comment]
OK, something has definitely changed now. We get two new nodes on the server (good), but only one gets linked to  the group (bad).

**Comment by DenoBeno** [comment]
OK, I'm closing this. Issues with assigning to the group are of a different nature.

**Comment by DenoBeno** [comment]
Oh, btw - could someone submit a new patch to https://www.drupal.org/project/business_rules/issues/3043752?
